---
- name: Install yum PostgreSQL repo
  when: ansible_os_family == "RedHat"
  block:
    - name: Install PostgreSQL yum repo
      ansible.builtin.yum:
        name: "{{ _postgresql_key }}"
        disable_gpg_check: true
      vars:
        _postgresql_distro: "EL-{{ ansible_distribution_major_version }}-x86_64"
        _postgresql_redhat: "{{ _postgresql_distro }}/pgdg-redhat-repo-latest.noarch.rpm"
        _postgresql_key: "https://download.postgresql.org/pub/repos/yum/reporpms/{{ _postgresql_redhat }}"
      changed_when: false

    - name: Update yum cache
      ansible.builtin.yum:
        update_cache: true
        disablerepo: "pgdg*"

- name: Install apt PostgreSQL repo
  when: ansible_os_family == "Debian"
  block:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - gpg-agent
          - gnupg
        update_cache: true

    - name: Install PostgreSQL apt key
      ansible.builtin.apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

    - name: Add apt repository
      ansible.builtin.apt_repository:
        filename: postgresql
        repo: "{{ _repo }}"
      vars:
        _repo_postgresql: "deb [arch=amd64,arm64]"
        _repo_ubuntu_url: "{{ _repo_postgresql }} http://apt.postgresql.org/pub/repos/apt"
        _repo: "{{ _repo_ubuntu_url }} {{ ansible_distribution_release | lower }}-pgdg main"
      changed_when: false

    - name: Install pgdg keyring
      ansible.builtin.apt:
        name: pgdg-keyring
        update_cache: true
